/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Ticket;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.services.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.UUID;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("welcome to IRCTC");
        UserBookingService userBookingService;

        try {
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("Something is wrong");
            return;
        }

        int option = 0;
        Scanner scan = new Scanner(System.in);

        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scan.nextInt();

            switch(option){

                case 1:
                    System.out.println("Enter username for signup");
                    String userNameSignup = scan.next();
                    System.out.println("Enter Password for SignUp");
                    String passwordSignUp = scan.next();
                    List<Ticket> ticketsBooked = new ArrayList<>();
                    User user = new User(userNameSignup, passwordSignUp, UserServiceUtil.hashPassword(passwordSignUp), ticketsBooked, UUID.randomUUID().toString());
                    userBookingService.signUp(user);
                    break;

                case 2:
                    System.out.println("Enter username for login");
                    String usernameLogin = scan.next();
                    System.out.println("Enter password for login");
                    String passwordLogin = scan.next();
                    User user1 = new User(usernameLogin, passwordLogin, UserServiceUtil.hashPassword(passwordLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(user1);
                    } catch (IOException e) {
                        System.out.println("Login failed");
                        return;
                    }
                    Boolean loggedIn = userBookingService.login();
                    if(loggedIn){
                        System.out.println("Login successful");
                    }else{
                        System.out.println("Login failed");
                    }
                    break;

                case 3:
                    System.out.println("Fetching all bookings");
                    userBookingService.fetchBooking();
                    break;
            }
        }
    }
}
