/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Ticket;
import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.TrainService;
import org.example.services.UserBookingService;
import org.example.services.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.UUID;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        System.out.println("welcome to IRCTC Booking App");
        UserBookingService userBookingService;

        try {
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("Something is wrong");
            return;
        }

        int option = 0;
        Scanner scan = new Scanner(System.in);
        String sourceSearch = "";
        String destinationSearch = "";

        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scan.nextInt();

            switch(option){

                case 1:
                    System.out.println("Enter username for signup");
                    String userNameSignup = scan.next();
                    System.out.println("Enter Password for SignUp");
                    String passwordSignUp = scan.next();
                    List<Ticket> ticketsBooked = new ArrayList<>();
                    User user = new User(userNameSignup, passwordSignUp, UserServiceUtil.hashPassword(passwordSignUp), ticketsBooked, UUID.randomUUID().toString());
                    userBookingService.signUp(user);
                    break;

                case 2:
                    System.out.println("Enter username for login");
                    String usernameLogin = scan.next();
                    System.out.println("Enter password for login");
                    String passwordLogin = scan.next();
                    User user1 = new User(usernameLogin, passwordLogin, UserServiceUtil.hashPassword(passwordLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(user1);
                    } catch (IOException e) {
                        System.out.println("Login failed");
                        return;
                    }
                    Boolean loggedIn = userBookingService.login();
                    if(loggedIn){
                        System.out.println("Login successful");
                    }else{
                        System.out.println("Login failed");
                    }
                    break;

                case 3:
                    System.out.println("Fetching all bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Enter source: ");
                    sourceSearch = scan.next();
                    System.out.println("Enter Destination: ");
                    destinationSearch = scan.next();
                    try{
                        TrainService trainService = new TrainService();
                        List<Train> lst = trainService.serachTrains(sourceSearch,destinationSearch);
                        trainService.printTrains(lst);
                    }catch(IOException ex) {
                        System.out.println("cannot fetch trains");
                        return;
                    }
                    break;

                case 5:
                    System.out.println("Please Enter The Train Number");
                    String trainNo = scan.next();
                    Train trainFound = null;
                    TrainService trainService = null;
                    try{
                        trainService = new TrainService();
                        trainFound = trainService.findByTrainNo(trainNo);
                    }catch(IOException ex) {
                        System.out.println("Train not Found");
                        return;
                    }
                    System.out.println("Enter train row for seat");
                    int r = scan.nextInt();
                    System.out.println("Enter train column for seat");
                    int c = scan.nextInt();
                    List<List<Integer>> seats = trainFound.getSeats();
                    int value = seats.get(r).get(c);
                    if(value==1){
                        System.out.println("Seat not available");
                        return;
                    }
                    seats.get(r).set(c,1);
                    trainFound.setSeats(seats);
                    trainService.saveTrainListToFile(trainFound);
                    try {
                        userBookingService.bookTicket(trainFound,sourceSearch,destinationSearch);
                        System.out.println("Booking successful");
                    }catch (IOException io){
                        System.out.println("Booking failed");
                    }
                    break;

                case 6:
                    try {
                        System.out.println("Enter ticketId");
                        String ticketId = scan.next();
                        userBookingService.cancelBooking(ticketId);
                    }catch (IOException io){
                        System.out.println("Something went wrong");
                    }
            }
        }
    }
}
